In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(
    "../data/raw/cardio_train.csv",
    sep=";"
)

df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [4]:
df.shape

(70000, 13)

In [5]:
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")

Rows: 70,000
Columns: 13

In [6]:
df.columns.tolist()

['id',
 'age',
 'gender',
 'height',
 'weight',
 'ap_hi',
 'ap_lo',
 'cholesterol',
 'gluc',
 'smoke',
 'alco',
 'active',
 'cardio']

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [8]:
df.describe()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,19468.865814,1.349571,164.359229,74.205690,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,2467.251667,0.476838,8.210126,14.395757,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,10798.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,17664.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,19703.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,21327.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,23713.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
df.isnull().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [10]:
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

In [11]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [12]:
print("Duplicate IDs:", df["id"].duplicated().sum())

Duplicate IDs: 0

In [13]:
categorical_columns = [
    "gender",
    "cholesterol",
    "gluc",
    "smoke",
    "alco",
    "active",
    "cardio"
]

for column in categorical_columns:
    print(f"\n{column}")
    print(df[column].value_counts().sort_index())

gender
gender
1    45530
2    24470
Name: count, dtype: int64

cholesterol
cholesterol
1    52385
2     9549
3     8066
Name: count, dtype: int64

gluc
gluc
1    59479
2     5190
3     5331
Name: count, dtype: int64

smoke
smoke
0    63831
1     6169
Name: count, dtype: int64

alco
alco
0    66236
1     3764
Name: count, dtype: int64

active
active
0    13739
1    56261
Name: count, dtype: int64

cardio
cardio
0    35021
1    34979
Name: count, dtype: int64

In [14]:
df.nsmallest(10, "height")[["height", "weight", "age"]]

       height  weight    age
22723      55    81.0  23386
66643      57    61.0  18830
64115      59    57.6  18426
29157      60    69.0  19088
27603      64    61.0  20978
33607      65    72.0  19709
44490      65    60.0  19120
64454      66    63.0  21348
14323      67    57.0  22005
50789      67    60.0  14499

In [15]:
df.nlargest(10, "height")[["height", "weight", "age"]]

       height  weight    age
6486      250    86.0  21220
21628     207    78.0  19054
41901     200   100.0  19187
1117      198    68.0  22156
3237      198    61.0  16072
8897      198    79.0  22497
12007     198   102.0  18258
29145     198    90.0  21812
30127     198    85.0  23274
30238     198    89.0  20381

In [16]:
df.nsmallest(10, "weight")[["height", "weight"]]

       height  weight
57858     165    10.0
33817     178    11.0
60188     162    21.0
29488     177    22.0
26806     157    23.0
34276     128    28.0
60699     171    29.0
3752      120    30.0
18559     160    30.0
41905     143    30.0

In [17]:
df.nlargest(10, "weight")[["height", "weight"]]

       height  weight
435       186   200.0
50413     180   200.0
61285     180   183.0
36780     161   181.0
4743      176   180.0
45378     190   180.0
60592     180   180.0
61362     196   180.0
20092     165   178.0
27384      80   178.0

In [18]:
df.nsmallest(15, "ap_hi")[["ap_hi", "ap_lo"]]

       ap_hi  ap_lo
35040   -150     80
23988   -140     90
25240   -120     80
46627   -120     80
16021   -115     70
4607    -100     80
20536   -100     70
8757       1   2088
42334      1   1088
5382       7     80
2612      10     70
20886     10     60
29170     10     70
56777     10     80
57909     10     60

In [19]:
df.nlargest(15, "ap_hi")[["ap_hi", "ap_lo"]]

       ap_hi  ap_lo
40852  16020     80
25464  14020     80
25519  14020     80
46912  14020     90
47253  14020     90
55459  13010     80
55847  13010     80
7763   11500     90
51438  11020     80
69370   2000    100
28147   1620     80
13895   1500     80
8915    1420     80
43208   1420     80
50836   1409     90

In [20]:
df.nsmallest(15, "ap_lo")[["ap_hi", "ap_lo"]]

       ap_hi  ap_lo
60106     15    -70
2014     906      0
13489    130      0
16459    138      0
17381    138      0
22923    149      0
23867    906      0
25454     12      0
27686    140      0
31783    907      0
38370    148      0
40330    309      0
41505    806      0
42397    906      0
43922    108      0

In [21]:
df.nlargest(15, "ap_lo")[["ap_hi", "ap_lo"]]

       ap_hi  ap_lo
43326    200  11000
2381     140  10000
23849    150  10000
68538    160  10000
43434    130   9800
6653     130   9100
12086    130   9011
32920    150   9011
15990    120   8500
44042    120   8200
20882    160   8100
17738    140   8099
37156    140   8099
38024    130   8099
23502    120   8079

In [22]:
(df["ap_hi"] <= 0).sum()

np.int64(7)

In [23]:
(df["ap_lo"] <= 0).sum()

np.int64(22)

In [24]:
(df["ap_hi"] < df["ap_lo"]).sum()

np.int64(1234)

In [25]:
invalid_ap_hi = ((df["ap_hi"] < 70) | (df["ap_hi"] > 250)).sum()
invalid_ap_lo = ((df["ap_lo"] < 40) | (df["ap_lo"] > 150)).sum()

print(invalid_ap_hi)
print(invalid_ap_lo)

229
1034

In [26]:
quality_summary = {
    "Issue": [
        "Missing values",
        "Duplicate rows",
        "Non-positive systolic BP",
        "Non-positive diastolic BP",
        "Systolic BP < diastolic BP",
        "Systolic BP outside 70–250",
        "Diastolic BP outside 40–150"
    ],
    "Count": [
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        (df["ap_hi"] <= 0).sum(),
        (df["ap_lo"] <= 0).sum(),
        (df["ap_hi"] < df["ap_lo"]).sum(),
        ((df["ap_hi"] < 70) | (df["ap_hi"] > 250)).sum(),
        ((df["ap_lo"] < 40) | (df["ap_lo"] > 150)).sum()
    ]
}

quality_summary = pd.DataFrame(quality_summary)

quality_summary["Percentage"] = (
    quality_summary["Count"] / len(df) * 100
).round(2)

quality_summary

                         Issue  Count  Percentage
0               Missing values      0        0.00
1               Duplicate rows      0        0.00
2     Non-positive systolic BP      7        0.01
3    Non-positive diastolic BP     22        0.03
4   Systolic BP < diastolic BP   1234        1.76
5   Systolic BP outside 70–250    229        0.33
6  Diastolic BP outside 40–150   1034        1.48

In [28]:
unique_bp_issues = bp_issues.any(axis=1).sum()

print(f"Unique records with BP issues: {unique_bp_issues}")
print(f"Percentage of dataset: {unique_bp_issues / len(df) * 100:.2f}%")

Unique records with BP issues: 1332
Percentage of dataset: 1.90%

In [29]:
issue_count = bp_issues.sum(axis=1)

print("Number of BP issues per record:")
print(issue_count.value_counts().sort_index())

Number of BP issues per record:
0    68668
1      160
2     1150
3       22
Name: count, dtype: int64

In [31]:
affected_bp = df.loc[bp_issues.any(axis=1)].copy()

affected_bp[["age", "height", "weight", "ap_hi", "ap_lo", "cardio"]].head(20)

        age  height  weight  ap_hi  ap_lo  cardio
228   17489     183    98.0    160   1100       1
241   21932     157    60.0    160   1000       1
260   18217     150    83.0    140    800       1
329   23407     176    63.0    160   1000       1
345   18704     154    81.0    140   1000       1
418   16658     157    72.0    150     30       1
473   15226     150    95.0    150   1033       1
474   19099     156    65.0    120    150       0
559   20430     173   101.0    200   1000       1
567   21281     168    78.0     14     90       1
613   18963     165    92.0    140   1000       1
636   20457     169    68.0     70    110       0
649   18190     166    57.0    190   1100       1
653   21842     156    72.0    180   1000       1
719   23407     170    74.0    140   1000       1
881   17405     170    84.0    150   1100       1
927   21867     175    70.0     14     90       1
979   18225     172    65.0     11     80       0
1000  21043     168    82.0    160   1000       1
1033  15906     167    71.0    150   1001       1

In [32]:
affected_bp.sort_values("ap_hi")[["age", "ap_hi", "ap_lo", "cardio"]].head(10)

         age  ap_hi  ap_lo  cardio
35040  23325   -150     80       1
23988  18301   -140     90       1
25240  14711   -120     80       1
46627  23646   -120     80       0
16021  22108   -115     70       0
20536  15581   -100     70       0
4607   15281   -100     80       0
42334  18716      1   1088       1
8757   16905      1   2088       0
5382   21240      7     80       0

In [33]:
affected_bp.sort_values("ap_hi", ascending=False)[
    ["age", "ap_hi", "ap_lo", "cardio"]
].head(10)

         age  ap_hi  ap_lo  cardio
40852  17438  16020     80       1
25519  21361  14020     80       1
46912  16910  14020     90       1
25464  15835  14020     80       1
47253  19731  14020     90       0
55847  23182  13010     80       0
55459  18307  13010     80       1
7763   21032  11500     90       1
51438  18784  11020     80       1
69370  14696   2000    100       1

In [34]:
affected_bp.sort_values("ap_lo")[["age", "ap_hi", "ap_lo", "cardio"]].head(10)

         age  ap_hi  ap_lo  cardio
60106  22571     15    -70       1
22923  21182    149      0       1
25454  17952     12      0       0
23867  16131    906      0       1
52580  21919     13      0       0
48049  19012    121      0       1
65303  23612    120      0       1
63787  14722    117      0       0
17381  18226    138      0       0
45835  19597    140      0       0

In [35]:
affected_bp.sort_values("ap_lo", ascending=False)[
    ["age", "ap_hi", "ap_lo", "cardio"]
].head(10)

         age  ap_hi  ap_lo  cardio
43326  23221    200  11000       1
68538  19062    160  10000       1
23849  18102    150  10000       1
2381   20994    140  10000       1
43434  21906    130   9800       0
6653   19528    130   9100       1
32920  18335    150   9011       1
12086  21466    130   9011       1
15990  14508    120   8500       0
44042  21220    120   8200       0